# Generated by Django 5.1.3 on 2024-12-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecycle', '0004_alter_day_options_alter_metacycle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacycle',
            name='user',
        ),
    ]
